Update README.md
Pkg.add("some-url") errors on Julia 1.7.3

```julia
import Pkg; Pkg.add("https://github.com/andreypopp/julia-repl-vim.git")
```
ERROR: `https://github.com/andreypopp/julia-repl-vim.git` is not a valid package name
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.

Changed to Pkg.add(url="some-url")